title = "Joakim Ysland"
baseURL = 'https://joakimysland.github.io/'
languageCode = 'en-us'
theme = "hugo-blog-awesome"

# To enable Google Analytics 4 (gtag.js) provide G-MEASUREMENT_ID below.
# To disable	Google Analytics, simply leave the field empty or remove the next line
googleAnalytics = '' # G-MEASUREMENT_ID

# Enable emojis globally
enableEmoji = true

# set markup.highlight.noClasses=false to enable code highlight
[markup]
	[markup.highlight]
		noClasses = false
	[markup.goldmark.renderer]
		unsafe = true

[security]
	enableInlineShortcodes = true

[menu]
	[[menu.main]] 
		# The page reference (pageRef) is useful for menu highlighting
		# When pageRef is set, setting `url` is optional; it will be used as a fallback if the page is not found.
		pageRef="/"
		name = 'Home'
		url = '/'
		weight = 10
	[[menu.main]]
		pageRef="entries"
		name = 'Entries'
		url = '/entries/'
		weight = 20
	# [[menu.main]]
	# 	pageRef="about"
	# 	name = 'About'
	# 	url = '/about/'
	# 	weight = 30

[params]
	sitename = "Joakim Ysland"
	defaultColor = "dark" # set default color mode: dark or light
	description = "Minimal Hugo blog theme with light and dark mode support"

[params.author]
	avatar = "avatar.png" # put the file in assets folder; also ensure that image has same height and width
	# Note: image is not rendered if the resource(avatar image) is not found. No error is displayed.
	intro = "Joakim Ysland"
	name = "Joakim Ysland"
	description = "Hello"
	
[[params.socialIcons]]
name = "github"
url = "https://github.com/JoakimYsland"

[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/joakimysland"

[[params.socialIcons]]
name = "artstation"
url = "https://www.artstation.com/joakimysland"

[[params.socialIcons]]
name = "instagram"
url = "https://www.instagram.com/joakimysland/"
